import { emitScript } from './emit';
import type { NewOp, Recording } from './types';

/**
 * Wraps an emitted reproduction script in a page that can be opened straight
 * from disk, pasted into JS Bin or attached to an issue.
 */

const MAP_ELEMENT_ID = 'map';

const PAGE_CSS = 'body{margin:0;font:13px/1.4 system-ui,sans-serif;background:#111;color:#eee}#map{max-width:100vw}';

const DEFAULT_SIZE = {width: 800, height: 600};

/**
 * Builds a self-contained HTML page that makes the recorded calls.
 *
 * The page is a module that imports MapLibre from unpkg and then runs the
 * calls as ordinary source - `new maplibregl.Map({...})`, `map.flyTo({...})` -
 * so whoever receives it can read it, edit it and cut it down to the smallest
 * case that still shows the bug.
 *
 * @param recording - the recording to turn into a page
 * @param fragment - emit only the body content, for hosts such as CodePen that
 * supply their own document skeleton
 * @returns the HTML source of the reproduction page
 */
export function buildReproPage(recording: Recording, fragment: boolean = false): string {
    const version = /^\d/.test(recording.maplibre) ? recording.maplibre : 'latest';
    const size = containerSize(recording);
    // A literal `</script` anywhere in the source - inside a recorded string, or
    // in the text of a callback - would end the script block early.
    const script = emitScript(recording).replace(/<\/script/gi, '<\\/script');
    const closeScript = '<\/script>';

    const body = [
        `<link rel="stylesheet" href="https://unpkg.com/maplibre-gl@${version}/dist/maplibre-gl.css" />`,
        `<style>${PAGE_CSS}</style>`,
        `<div id="${MAP_ELEMENT_ID}" style="width:${size.width}px;height:${size.height}px"></div>`,
        '<script type="module">',
        `import * as maplibregl from 'https://unpkg.com/maplibre-gl@${version}/dist/maplibre-gl.mjs';`,
        '',
        script,
        closeScript
    ].join('\n');

    if (fragment) return body;

    return [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="utf-8" />',
        '<meta name="viewport" content="width=device-width, initial-scale=1" />',
        '<title>MapLibre GL JS reproduction</title>',
        '<!--',
        '  Generated by the experimental MapLibre GL JS call recorder.',
        `  recorder:     ${recording.recorder}`,
        `  maplibre-gl:  ${recording.maplibre}`,
        `  recorded at:  ${recording.createdAt}`,
        `  user agent:   ${recording.env.userAgent}`,
        `  dpr:          ${recording.env.devicePixelRatio}`,
        `  viewport:     ${recording.env.viewport?.join(' x ')}`,
        `  operations:   ${recording.ops.length}`,
        '-->',
        '</head>',
        '<body>',
        body,
        '</body>',
        '</html>'
    ].join('\n');
}

/**
 * The size the map element gets. The size recorded alongside the first map is
 * the most faithful; `recording.container` is the fallback for a map that was
 * already gone by the time the recording was exported.
 */
function containerSize(recording: Recording): {width: number; height: number} {
    const created = recording.ops.find((op): op is NewOp => op.k === 'new' && op.c === 'Map');
    const recorded = (created?.a[0] as Record<string, any> | undefined)?.['__containerSize'];
    if (Array.isArray(recorded)) return {width: recorded[0], height: recorded[1]};
    return recording.container ?? DEFAULT_SIZE;
}
